### ISSUE TITLE
Duplicate readmes for the examples

### ISSUE THREAD

**Issue by JGL** [nickgillian/ofxGrt#12]
I was just taking a look at:

https://github.com/nickgillian/ofxGrt/tree/master/example_kinect_posture_regression

And noticed that all the readmes for the example projects are the readme for Gyrosc Orientation Example - it looks like they have all been duplicated.

**Comment by narner** [comment]
@nickgillian I was actually about to email you about this until I saw this issue, as I may be using the GRT for a Kinect project. All the Kinect examples have the Gyrosc readme.

**Comment by JStrats** [comment]
@nickgillian the right readme files for the Kinect examples are still missing, could you fix this?
