### ISSUE TITLE
Allow highlighting and labeling of sections of an ofxGrtTimeseriesPlot.

### ISSUE THREAD

**Issue by damellis** [nickgillian/ofxGrt#9]
It can be useful to highlight and label sections of a plot, e.g. to show predictions of a machine learning pipeline overlaid on live data:

![screen shot 2016-04-21 at 3 20 01 pm](https://cloud.githubusercontent.com/assets/405058/14726113/c65ce222-07d4-11e6-8ba3-932a4be2b4b5.png)

Here's an example of how it might be implemented: https://github.com/nebgnahz/ofxGrt/commit/69382f2e2a4ef2728f00e2c183444e1efd40a28f

It might also be good to add contrasting vertical lines (e.g. in white) at the start, and possibly the end, of each highlighted interval.

Again, if this seems useful, I can work on a proper pull request.

**Comment by nickgillian** [comment]
yes, this would be very useful. I can integrate things if you setup a pull request.

**Comment by damellis** [comment]
Thanks!
